CREATE
OR REPLACE VIEW LATEST_NUMBER_OF_CASES AS WITH CASES_CTE AS (
    SELECT
        *
    FROM
        public.covid_19_cases_and_death
    WHERE
        indicator = 'cases'
),
MAX_YEAR_WEEK_BY_COUNTRY_CTE AS (
    SELECT
        MAX(CAST(REPLACE(YEAR_WEEK, '-', '') AS INTEGER)) :: INTEGER AS YEAR_WEEK,
        COUNTRY
    FROM
        CASES_CTE
    GROUP BY
        COUNTRY
)
SELECT
    A.COUNTRY,
    A.COUNTRY_CODE,
    A.CONTINENT,
    A.POPULATION,
    A.INDICATOR,
    A.WEEKLY_COUNT,
    A.YEAR_WEEK,
    A.RATE_14_DAY,
    A.CUMULATIVE_COUNT,
    A.SOURCE,
    A.META_EXTRACTED_DATE
FROM
    CASES_CTE A
    INNER JOIN MAX_YEAR_WEEK_BY_COUNTRY_CTE B ON REPLACE(A.YEAR_WEEK, '-', '') :: INTEGER = B.YEAR_WEEK
    AND A.COUNTRY = B.COUNTRY;