-- Query #3
WITH RICHEST_COUNTRIES_CTE AS (
    SELECT
        *
    FROM
        public.countries_of_the_world
    WHERE
        GDP_DOLLAR_PER_CAPITA IS NOT NULL
    ORDER BY
        GDP_DOLLAR_PER_CAPITA DESC
    LIMIT
        20
), CASES_BY_RICH_COUNTRIES AS (
    SELECT
        A.COUNTRY,
        A.CUMULATIVE_COUNT
    FROM
        public.covid_19_cases_and_death A
        INNER JOIN RICHEST_COUNTRIES_CTE B ON A.COUNTRY = B.COUNTRY
)
SELECT
    COUNTRY,
    MAX(CUMULATIVE_COUNT) AS MAX_CUMULATIVE_COUNT
FROM
    CASES_BY_RICH_COUNTRIES
GROUP BY
    COUNTRY
ORDER BY
    MAX_CUMULATIVE_COUNT DESC
LIMIT
    10;