CREATE
OR REPLACE VIEW ENRICHED_COVID_DATA AS WITH VACCINATION_CTE AS (
    SELECT
        *,
        TO_CHAR(FULL_DATE :: DATE, 'YYYY-WW') AS YEAR_WEEK
    FROM
        public.vaccination_by_country
),
VACCINATION_BY_YEAR_WEEK_CTE AS (
    SELECT
        LOCATION,
        YEAR_WEEK,
        SUM(TESTS_PER_CASE) AS TESTS_PER_CASE,
        SUM(TOTAL_VACCINATIONS) AS TOTAL_VACCINATIONS,
        SUM(PEOPLE_VACCINATED) AS PEOPLE_VACCINATED,
        SUM(PEOPLE_FULLY_VACCINATED) AS PEOPLE_FULLY_VACCINATED
    FROM
        VACCINATION_CTE
    GROUP BY
        LOCATION,
        YEAR_WEEK
)
SELECT
    A.*,
    B.TESTS_PER_CASE,
    B.TOTAL_VACCINATIONS,
    B.PEOPLE_VACCINATED,
    B.PEOPLE_FULLY_VACCINATED
FROM
    public.covid_19_cases_and_death A
    LEFT JOIN VACCINATION_BY_YEAR_WEEK_CTE B ON A.country = B.location
    AND A.YEAR_WEEK = B.YEAR_WEEK;